for file in /etc/bash.bashrc /etc/bashrc
do
  [ -f $file ] && source $file
done

function parse_git_branch() {
  git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}

function git_repo_name() {
  basename `git rev-parse --show-toplevel 2> /dev/null` | sed 's/ *$//g'
}

alias vi='vim'
alias vpn='sudo openconnect -s /etc/vpnc/vpnc-script'
alias tig='git'
alias tgi='git'
alias tgit='git'
alias giti='git'
alias itg='git'
alias igt='git'
alias scp='scp -C'
alias tmxu='tmux'
alias less='less -f'
alias lll='ls -larth'
alias sl='ls'
alias lls='ls'
alias l='ls'
alias lss='ls'
alias sbrc='source ~/.bashrc'
alias g='git'
alias tmu='tmux'
alias ipa='ip a'
alias ks='ls'
alias vu='vim'
alias d='cd'
alias gits='git status'
alias fidn='find'

# If i actually need `dc` I will call it from its full path
alias dc='cd'

function cdl {
  cd $1
  ls
}

set -o vi

export PS1="\e[0;32m\u@\h\e[m \e[0;36m\w\e[m \e[0;35m[\t]\e[m \e[0;33m\$(git rev-parse --abbrev-ref HEAD 2> /dev/null | sed 's/.*/(&)/')\e[m\n> "
export PS2="-> "

export LYNX_CFG=~/.lynx.cfg
export PATH=~/.bin:/usr/local/bin:$PATH

[ -f ~/.custom_bashrc ] && source ~/.custom_bashrc

alias ls='ls -h --color'
alias lx='ls -lXB'         #  Sort by extension.
alias lk='ls -lSr'         #  Sort by size, biggest last.
alias lt='ls -ltr'         #  Sort by date, most recent last.
alias lc='ls -ltcr'        #  Sort by/show change time,most recent last.
alias lu='ls -ltur'        #  Sort by/show access time,most recent last.

# The ubiquitous 'll': directories first, with alphanumeric sorting:
alias ll="ls -lv --group-directories-first"
alias lm='ll |more'        #  Pipe through 'more'
alias lr='ll -R'           #  Recursive ls.
alias la='ll -A'           #  Show hidden files.
alias tree='tree -Csuh'    #  Nice alternative to 'recursive ls' ...

eval "`dircolors`"

